schema_version = "1.0.0"


id = "Industrial_AOV_Connector"
version = "3.0.4"
name = "Industrial AOV Connector"
tagline = "Auto generate outputs for advanced compositing"
maintainer = "Roland Vyens"


type = "add-on"


website = "https://github.com/RolandVyens/Industrial-AOV-Connector"


tags = ["Compositing", "Import-Export", "Pipeline", "Render"]


blender_version_min = "4.2.0"


license = [
  "SPDX:GPL-3.0-or-later",
]


[permissions]
files = "Delete Useless Default Renders button need this"